CREATE DATABASE IF NOT EXISTS grocery;
CREATE TABLE IF NOT EXISTS grocery.events (event_id UUID, event_type LowCardinality(String), event_time DateTime64(3, 'UTC'), source LowCardinality(String), store_id String, product_id String, supplier_id String, quantity Float64, unit_price Float64, expected_delivery_time Nullable(DateTime64(3, 'UTC')), actual_delivery_time Nullable(DateTime64(3, 'UTC')), payload String, ingested_at DateTime DEFAULT now()) ENGINE=ReplacingMergeTree(ingested_at) PARTITION BY toYYYYMM(event_time) ORDER BY (event_type, event_time, event_id);
CREATE TABLE IF NOT EXISTS grocery.dim_products (product_id String, product_name String, category String, subcategory String, perishability UInt8, unit_price Float64, supplier_id String) ENGINE=ReplacingMergeTree ORDER BY product_id;
CREATE TABLE IF NOT EXISTS grocery.dim_stores (store_id String, store_name String, city String, region String, latitude Float64, longitude Float64, store_type String) ENGINE=ReplacingMergeTree ORDER BY store_id;
CREATE TABLE IF NOT EXISTS grocery.dim_suppliers (supplier_id String, supplier_name String, country String, reliability_score Float64, lead_time_days UInt8) ENGINE=ReplacingMergeTree ORDER BY supplier_id;
CREATE TABLE IF NOT EXISTS grocery.fact_orders (event_id UUID, event_time DateTime64(3,'UTC'), store_id String, product_id String, quantity Float64, unit_price Float64) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (store_id, product_id, event_time);
CREATE TABLE IF NOT EXISTS grocery.fact_inventory (event_id UUID, event_time DateTime64(3,'UTC'), store_id String, product_id String, quantity Float64, reorder_point Float64, safety_stock Float64, recommended_order_quantity Float64 DEFAULT 0) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (store_id, product_id, event_time);
CREATE TABLE IF NOT EXISTS grocery.fact_deliveries (event_id UUID, event_time DateTime64(3,'UTC'), supplier_id String, store_id String, product_id String, ordered_quantity Float64, delivered_quantity Float64, expected_delivery_time Nullable(DateTime64(3,'UTC')), actual_delivery_time Nullable(DateTime64(3,'UTC')), status String, source LowCardinality(String) DEFAULT 'simulator') ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (supplier_id, event_time);
CREATE TABLE IF NOT EXISTS grocery.fact_prices (event_id UUID, event_time DateTime64(3,'UTC'), product_id String, unit_price Float64) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (product_id, event_time);
CREATE TABLE IF NOT EXISTS grocery.fact_demand (event_id UUID, event_time DateTime64(3,'UTC'), store_id String, product_id String, quantity Float64, requested_quantity Float64 DEFAULT 0, lost_sales_quantity Float64 DEFAULT 0, promotion UInt8 DEFAULT 0) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (product_id, store_id, event_time);
CREATE TABLE IF NOT EXISTS grocery.fact_supply_chain_alerts (alert_id UUID, event_time DateTime64(3,'UTC'), alert_type LowCardinality(String), severity LowCardinality(String), store_id String, product_id String, supplier_id String, message String) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (severity, event_time);
CREATE TABLE IF NOT EXISTS grocery.model_outputs (event_time DateTime64(3,'UTC'), store_id String, product_id String, predicted_demand Float64, anomaly_score Float64, model LowCardinality(String)) ENGINE=MergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (product_id, store_id, event_time);

CREATE TABLE IF NOT EXISTS grocery.fact_waste (event_id UUID, event_time DateTime64(3,'UTC'), store_id String, product_id String, quantity Float64, unit_cost Float64, reason LowCardinality(String)) ENGINE=ReplacingMergeTree PARTITION BY toYYYYMM(event_time) ORDER BY (event_id);
